version: '3.8'

services:
  server:
    build: .
    command: python src/server.py
    ports:
      - "65432:65432"

  client:
    build: .
    command: python src/client.py
    depends_on:
      - server
